apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: globeco-pricing-service
  namespace: globeco
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: globeco-pricing-service
  minReplicas: 1
  maxReplicas: 100
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80 